"""add_floor_to_parking_spots

Revision ID: 53aba8bb95f0
Revises: cc4b1138d2de
Create Date: 2026-03-06 13:22:42.545043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53aba8bb95f0'
down_revision: Union[str, None] = 'cc4b1138d2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add floor column with a server default so existing rows get a value
    op.add_column('parking_spots', sa.Column('floor', sa.Integer(), nullable=False, server_default='1'))
    op.create_index(op.f('ix_parking_spots_floor'), 'parking_spots', ['floor'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parking_spots_floor'), table_name='parking_spots')
    op.drop_column('parking_spots', 'floor')
    # ### end Alembic commands ###
