"""database schema v2

Revision ID: d4b0d15883de
Revises: 53aba8bb95f0
Create Date: 2026-03-26 01:13:08.488092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4b0d15883de'
down_revision: Union[str, None] = '53aba8bb95f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricing_rules', sa.Column('rush_multiplier', sa.Float(), nullable=False))
    op.add_column('pricing_rules', sa.Column('is_rush_now', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricing_rules', 'is_rush_now')
    op.drop_column('pricing_rules', 'rush_multiplier')
    # ### end Alembic commands ###
